Anpassung configure.sh an to.science.api 2022

diff --git a/templates/toscience-api b/templates/toscience-api
--- a/templates/toscience-api
+++ b/templates/toscience-api
@@ -2,6 +2,7 @@
 #
 # /etc/init.d/regal-api 
 # Modified by Jan Schnasse schnasse@gmx.de
+# Modified by Ingolf Kuss und Nikolas Weger
 #
 # Written by Miquel van Smoorenburg <miquels@cistron.nl>.
 # Modified for Debian GNU/Linux by Ian Murdock <imurdock@gnu.ai.mit.edu>.
@@ -29,12 +30,12 @@ set -e
 #Variables can be overwritten with $DEFAULT 
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
 NAME=regal-api
-DESC="Regal Api"
+DESC="Toscience Api"
 JAVA_HOME=/opt/java
 JAVA_OPTS="-XX:+HeapDumpOnOutOfMemoryError"
-HOME="$ARCHIVE_HOME/regal-server"
-USER="$REGAL_USER"
-GROUP="$REGAL_GROUP"
+HOME="$ARCHIVE_HOME/toscience-server"
+USER="$LINUX_USER"
+GROUP="$LINUX_GROUP"
 SECRET="$PLAY_SECRET"
 
 export JAVA_HOME
@@ -57,7 +58,7 @@ if [ -r /etc/default/locale ]; then
 export LANG
 fi
  
-. /lib/lsb/init-functions
+# . /lib/lsb/init-functions
  
 if [ -r /etc/default/rcS ]; then
 . /etc/default/rcS
@@ -83,16 +84,19 @@ app_start() {
 case "$1" in
 start)
 	if [ -z "$JAVA_HOME" ]; then
-		log_failure_msg "no JDK found - please set JAVA_HOME"
+		echo "ERR: no JDK found - please set JAVA_HOME"
+		# log_failure_msg "no JDK found - please set JAVA_HOME"
 		exit 1
 	fi
 	 
 	if [ ! -d "$HOME/conf" ]; then
-		log_failure_msg "invalid HOME: $HOME"
+		echo "ERR: invalid HOME: $HOME"
+		# log_failure_msg "invalid HOME: $HOME"
 		exit 1
 	fi
 	 
-	log_daemon_msg "Starting $DESC" "$NAME"
+	echo "INFO: Starting $DESC" "$NAME"
+	# log_daemon_msg "Starting $DESC" "$NAME"
 	if start-stop-daemon --test --start --pidfile "$PID" \
 	--user $USER --exec "$JAVA_HOME/bin/java" \
 	>/dev/null; then
@@ -103,35 +107,45 @@ start)
 			if [ -f "$PID" ]; then
 				rm -f "$PID"
 			fi
-			log_end_msg 1
+			exit 1
+			# log_end_msg 1
 		else
-			log_end_msg 0
+			exit 0
+			# log_end_msg 0
 		fi
-		log_end_msg 0
+		exit 0
+		# log_end_msg 0
 	else
-		log_progress_msg "(already running)"
-		log_end_msg 0
+		echo "INFO: (already running)"
+		# log_progress_msg "(already running)"
+		exit 0
+		# log_end_msg 0
 	fi
 ;;
 stop)
-	log_daemon_msg "Stopping $DESC" "$NAME"
+	echo "INFO: Stopping $DESC" "$NAME"
+	# log_daemon_msg "Stopping $DESC" "$NAME"
 	set +e
 	if [ -f "$PID" ]; then
 		start-stop-daemon --stop --pidfile "$PID" \
 		--user "$USER" \
 		--retry=TERM/20/KILL/5 >/dev/null
 	if [ $? -eq 1 ]; then
-		log_progress_msg "$DESC is not running but pid file exists, cleaning up"
+		echo "INFO: $DESC is not running but pid file exists, cleaning up"
+		# log_progress_msg "$DESC is not running but pid file exists, cleaning up"
 	elif [ $? -eq 3 ]; then
 		PID="`cat $PID`"
-		log_failure_msg "Failed to stop $NAME (pid $PID)"
+		echo "ERR: Failed to stop $NAME (pid $PID)"
+		# log_failure_msg "Failed to stop $NAME (pid $PID)"
 		exit 1
 	fi
 		rm -f "$PID"
 	else
-		log_progress_msg "(not running)"
+		echo "INFO:(not running)"
+		# log_progress_msg "(not running)"
 	fi
-		log_end_msg 0
+		exit 0
+		# log_end_msg 0
 	set -e
 ;;
 status)
@@ -142,19 +156,23 @@ status)
 	if [ "$?" = "0" ]; then
 	 
 		if [ -f "$PID" ]; then
-			log_success_msg "$DESC is not running, but pid file exists."
+			echo "INFO: $DESC is not running, but pid file exists."
+			# log_success_msg "$DESC is not running, but pid file exists."
 			exit 1
 		else
-			log_success_msg "$DESC is not running."
+			echo "INFO: $DESC is not running."
+			# log_success_msg "$DESC is not running."
 			exit 3
 		fi
 	else
-		log_success_msg "$DESC is running with pid `cat $PID`"
+		echo "INFO: $DESC is running with pid `cat $PID`"
+		# log_success_msg "$DESC is running with pid `cat $PID`"
 	fi
 		set -e
 	;;
 *)
-	log_success_msg "Usage: $0 {start|stop|restart|status}"
+	echo "INFO: Usage: $0 {start|stop|restart|status}"
+	# log_success_msg "Usage: $0 {start|stop|restart|status}"
 	exit 1
 ;;
 esac
